sequenceDiagram
    participant Linky as Compteur Linky
    participant RPI as RPI-01<br/>Raspberry Pi Linky
    participant MQTT as Mosquitto<br/>HA-01
    participant HA as Home Assistant<br/>HA-01

    Linky->>RPI: Téléinfo série
    RPI->>MQTT: Publication MQTT
    MQTT->>HA: Messages MQTT