flowchart TD
    Internet((Internet))
    BOX["BOX-01<br/>Freebox Pop"]
    SW1["SW-01<br/>TRENDnet TEG-S762"]
    SW2["SW-02<br/>TRENDnet TEG-S762"]
    SW3["SW-03<br/>Linksys 5 ports 1 Gb"]
    AP["AP-01<br/>Linksys LAPAC1750"]
    HA["HA-01<br/>Home Assistant Green"]
    RPI_LINKY["RPI-01<br/>Raspberry Pi Linky"]
    RPI_ZWAVE["RPI-02<br/>Raspberry Pi Z-Wave"]

    Internet --> BOX
    BOX -- "2.5 Gb" --> SW1
    SW1 -- "10 Gb" --> SW2
    SW2 -- "1 Gb" --> SW3
    SW1 -- "1 Gb" --> AP
    AP -. "Wi-Fi" .-> RPI_LINKY
    SW3 -- "1 Gb" --> HA
    SW3 -- "1 Gb" --> RPI_ZWAVE